### ISSUE TITLE
Funkcja get_cart została wywołana nieprawidłowo

### ISSUE THREAD

**Issue by infokurs** [tpay-com/tpay-woocommerce#18]
ver 1.6.4
PHP 8.1, WP 6.6.1, WC 8.9.3

PHP Notice:  Funkcja get_cart została wywołana nieprawidłowo. Funkcja "Get cart" nie powinna być wywołana przed akcją wp_loaded. Backtrace: require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, Automattic\WooCommerce\Blocks\BlockTypesController->register_blocks, Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->__construct, Automattic\WooCommerce\Blocks\BlockTypes\Cart->initialize, Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->initialize, Automattic\WooCommerce\Blocks\BlockTypes\Cart->register_block_type_assets, Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->register_block_type_assets, Automattic\WooCommerce\Blocks\Assets\Api->register_script, apply_filters('woocommerce_blocks_register_script_dependencies'), WP_Hook->apply_filters, Automattic\WooCommerce\Blocks\Payments\Api->add_payment_method_script_dependencies, Automattic\WooCommerce\Blocks\Payments\PaymentMethodRegistry->get_all_active_payment_method_script_dependencies, Automattic\WooCommerce\Blocks\Payments\PaymentMethodRegistry->get_all_active_registered, array_filter, Automattic\WooCommerce\Blocks\Payments\PaymentMethodRegistry->Automattic\WooCommerce\Blocks\Payments\{closure}, Tpay\Blocks\TpayBlock->is_active, Tpay\TpayGateways->is_available, WC_Cart->get_cart, wc_doing_it_wrong Dowiedz się więcej: <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugowanie w WordPressie</a>. (Ten komunikat został dodany w wersji 2.3.) in /home/public_html/wp-includes/functions.php on line 6085

**Comment by s4ddly** [comment]
Gonna be fixed in #21
