### ISSUE TITLE
Logged errors when using Blik

### ISSUE THREAD

**Issue by remderk** [tpay-com/tpay-woocommerce#2]
Hi, 
I noticed that there were errors in the logs related to Blik payment  directly on the checkout.
PHP Version: 8.0
Woo: 8.6.1
WP: 6.4.3
TPay payments: 1.4.2

Tpay Panel:
In the list of notifications in the tpay panel in the column "Opis błędu" it shows: 
`Notice: Funkcja is_internal_meta_key została wywołana nieprawidłowo. Do wewnętrzn`

Error Log:
`[26-Mar-2024 11:04:00 UTC] ID was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, Tpay\TpayBlik->process_payment, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.`

`[26-Mar-2024 11:05:44 UTC] ID was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, Tpay\TpayBlik->process_payment, Tpay\TpayGateways->set_payment_data, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.`

`[26-Mar-2024 11:05:46 UTC] is_internal_meta_key was called incorrectly. Do wewnętrznych metod meta nie należy używać ogólnych metod dodawania/aktualizacji/pobierania metadanych, w tym "_payment_method". Użyj getterów i setterów. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, Tpay\TpayBlik->process_payment, Tpay\TpayBlik->process_transaction, WC_Data->update_meta_data, WC_Data->is_internal_meta_key, wc_doing_it_wrong. This message was added in version 3.2.0.`

`[26-Mar-2024 11:06:02 UTC] is_internal_meta_key was called incorrectly. Do wewnętrznych metod meta nie należy używać ogólnych metod dodawania/aktualizacji/pobierania metadanych, w tym "_transaction_id". Użyj getterów i setterów. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, Tpay\TpayBlik->process_payment, WC_Data->update_meta_data, WC_Data->is_internal_meta_key, wc_doing_it_wrong. This message was added in version 3.2.0.`

`[26-Mar-2024 11:06:02 UTC] is_internal_meta_key was called incorrectly. Do wewnętrznych metod meta nie należy używać ogólnych metod dodawania/aktualizacji/pobierania metadanych, w tym "_payment_method". Użyj getterów i setterów. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, Tpay\TpayBlik->process_payment, WC_Data->update_meta_data, WC_Data->is_internal_meta_key, wc_doing_it_wrong. This message was added in version 3.2.0.`

**Comment by s4ddly** [comment]
Following issue was resolved.
