### ISSUE TITLE
Disable autoload for option starting from tpay_status_

### ISSUE THREAD

**Issue by remderk** [tpay-com/tpay-woocommerce#28]
I noticed that autoload for us increased terribly in the database and the cause was generated by option_name starting with: tpay_status_ eg. tpay_status_1710335837___0, tpay_status_1710335838___1 etc

We had more than 3 thousand of them which increased the autoload from 700 Kb to more than 3 MB which is not good.

**Comment by mch0lic** [comment]
There is also "PROCESS_TRANSACTION" and "tpay_IPN" and it's also autoloaded. wp_options table is intended for settings, not for logging, place holding, etc. This info could be stored as order meta, or if that does not meet your needs, please, create a custom table and write it there. 

Current "practice" creates a lot of bloat in wp_options table, and it's very taxing on mysql on high traffic ecommerce sites.

**Comment by remderk** [comment]
Same for tpay_IPNXXX

**Comment by s4ddly** [comment]
Following issues has been resolved in version 1.7.0.
